import Head from 'next/head'
import Image from 'next/image'
import WelcomeContainer from "../containers/WelcomeContainer";
import {useState, useEffect} from "react";
import Header from "../containers/Header";
import ThemeContext from "../context/themeContext";
import About from '../containers/About'
import Projects from '../containers/Projects'
import Contact from '../containers/Contact'


export default function Home() {
  const [fs, setFs] = useState(false);
  const theme = Math.floor(Math.random() * 5) + 1;

useEffect(() => {
setTimeout(() => {
setFs(true);
}, 3100);
});
  return (
    <ThemeContext.Provider value={theme}>
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

    <div>
      <WelcomeContainer />
      {fs ? <>
      <Header></Header>
      <About></About>
      <Projects></Projects>
      <Contact></Contact>
      </>
       : <></>}
    </div>
    </div>
    </ThemeContext.Provider>
  )
}
